export {default as Home} from './Home/Home'
export {default as About} from './About/About'
export {default as Services} from './Services/Services'
export {default as LatestNews} from './LatestNews/LatestNews'
export {default as Contact} from './Contact/Contact'
export {default as NotFound} from './NotFound/NotFound'